/** Notification type constants — matches Prisma NotificationType enum */
export const NOTIFICATION_TYPE = {
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  REFUND_PROCESSED: 'REFUND_PROCESSED',
  TRIP_REMINDER: 'TRIP_REMINDER',
  REVIEW_REQUEST: 'REVIEW_REQUEST',
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  ORGANIZER_APPROVED: 'ORGANIZER_APPROVED',
  ORGANIZER_REJECTED: 'ORGANIZER_REJECTED',
  TRIP_REQUEST_RECEIVED: 'TRIP_REQUEST_RECEIVED',
  TRIP_REQUEST_APPROVED: 'TRIP_REQUEST_APPROVED',
  TRIP_REQUEST_REJECTED: 'TRIP_REQUEST_REJECTED',
  TRIP_REQUEST_EXPIRED: 'TRIP_REQUEST_EXPIRED',
  ADMIN_SUPPORT_MESSAGE: 'ADMIN_SUPPORT_MESSAGE',
  SYSTEM_ALERT: 'SYSTEM_ALERT',
} as const

/** Notification channel constants — matches Prisma NotificationChannel enum */
export const NOTIFICATION_CHANNEL = {
  IN_APP: 'IN_APP',
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  PUSH: 'PUSH',
} as const
