#!/bin/bash

# Travel App — Production Deployment Script
# Single command deployment modeled on Jebbly's deploy-local.sh
# Usage: ./scripts/deploy-prod.sh
#
# What it does:
# 1. Checks Docker is installed
# 2. Creates swap if low memory (for next build)
# 3. Auto-detects server IP
# 4. Generates .env.prod with strong random secrets (first run only)
# 5. Builds Docker images (API + Web + Nginx)
# 6. Starts Postgres + Redis, runs migrations
# 7. Starts API + Web + Nginx, runs health checks
# 8. Prints service URLs

set -e

# ── Colors ────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

COMPOSE_FILE="docker-compose.prod.yml"
ENV_FILE=".env.prod"
TOTAL_STEPS=8

# Navigate to project root (script may be called from anywhere)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

echo -e "${CYAN}"
echo "╔════════════════════════════════════════════╗"
echo "║   Travel App — Production Deployment       ║"
echo "╚════════════════════════════════════════════╝"
echo -e "${NC}"

# ══════════════════════════════════════════════════════
# Step 1: Check Docker
# ══════════════════════════════════════════════════════
echo -e "${YELLOW}[1/$TOTAL_STEPS] Checking Docker...${NC}"

if ! command -v docker &> /dev/null; then
    echo -e "${RED}Docker is not installed. Install Docker first:${NC}"
    echo "  curl -fsSL https://get.docker.com | sh"
    echo "  sudo usermod -aG docker \$USER"
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo -e "${RED}Docker Compose V2 is not available.${NC}"
    exit 1
fi

echo -e "${GREEN}  Docker $(docker --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+') + Compose $(docker compose version --short)${NC}"

# ══════════════════════════════════════════════════════
# Step 2: Check/Create Swap (next build needs ~2GB RAM)
# ══════════════════════════════════════════════════════
echo -e "${YELLOW}[2/$TOTAL_STEPS] Checking memory...${NC}"

if command -v free &> /dev/null; then
    TOTAL_RAM_MB=$(free -m | awk '/Mem:/ {print $2}')
    echo -e "  RAM: ${TOTAL_RAM_MB}MB"

    if [ "$TOTAL_RAM_MB" -lt 3000 ]; then
        if [ ! -f /swapfile ]; then
            echo -e "${YELLOW}  Low RAM. Creating 2GB swap file...${NC}"
            sudo fallocate -l 2G /swapfile 2>/dev/null || sudo dd if=/dev/zero of=/swapfile bs=1M count=2048
            sudo chmod 600 /swapfile
            sudo mkswap /swapfile
            sudo swapon /swapfile
            # Persist across reboots
            if ! grep -q '/swapfile' /etc/fstab 2>/dev/null; then
                echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab > /dev/null
            fi
            echo -e "${GREEN}  Swap created and enabled${NC}"
        else
            echo -e "${GREEN}  Swap file already exists${NC}"
        fi
    else
        echo -e "${GREEN}  Sufficient RAM${NC}"
    fi
else
    echo -e "  (skipping memory check — not Linux)"
fi

# ══════════════════════════════════════════════════════
# Step 3: Detect Server IP
# ══════════════════════════════════════════════════════
echo -e "${YELLOW}[3/$TOTAL_STEPS] Detecting server IP...${NC}"

SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "")
if [ -z "$SERVER_IP" ]; then
    SERVER_IP=$(curl -s --max-time 5 ifconfig.me 2>/dev/null || echo "localhost")
fi

echo -e "  Detected IP: ${CYAN}$SERVER_IP${NC}"
read -p "  Use this IP? (y/n or enter custom IP): " USER_INPUT

if [ "$USER_INPUT" != "y" ] && [ "$USER_INPUT" != "Y" ]; then
    if [ -n "$USER_INPUT" ] && [ "$USER_INPUT" != "n" ] && [ "$USER_INPUT" != "N" ]; then
        SERVER_IP="$USER_INPUT"
    else
        read -p "  Enter server IP: " SERVER_IP
    fi
fi

echo -e "${GREEN}  Using: $SERVER_IP${NC}"

# ══════════════════════════════════════════════════════
# Step 4: Generate .env.prod (first run only)
# ══════════════════════════════════════════════════════
echo -e "${YELLOW}[4/$TOTAL_STEPS] Configuring environment...${NC}"

if [ ! -f "$ENV_FILE" ]; then
    echo -e "  Generating ${ENV_FILE} with strong secrets..."

    POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)
    REDIS_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)
    JWT_SECRET=$(openssl rand -base64 48 | tr -d '/+=' | head -c 48)
    JWT_REFRESH_SECRET=$(openssl rand -base64 48 | tr -d '/+=' | head -c 48)

    BASE_URL="http://$SERVER_IP"
    SERVER_NAME="_"

    cat > "$ENV_FILE" << EOF
# ─── Auto-generated by deploy-prod.sh ────────────────
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Re-running deploy-prod.sh will NOT overwrite this file.

# ─── Server ──────────────────────────────────────────
SERVER_IP=$SERVER_IP
SERVER_NAME=$SERVER_NAME
WEB_PORT=3000
# Set DOMAIN to enable HTTPS (Phase 2):
# DOMAIN=tripcompare.in
# ACME_EMAIL=you@email.com

# ─── Database ────────────────────────────────────────
POSTGRES_USER=travel_user
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=travel_prod

# ─── Redis ───────────────────────────────────────────
REDIS_PASSWORD=$REDIS_PASSWORD

# ─── Auth ────────────────────────────────────────────
JWT_SECRET=$JWT_SECRET
JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# ─── Razorpay ───────────────────────────────────────
RAZORPAY_KEY_ID=
RAZORPAY_KEY_SECRET=
RAZORPAY_WEBHOOK_SECRET=

# ─── Cloudinary ─────────────────────────────────────
CLOUDINARY_CLOUD_NAME=
CLOUDINARY_API_KEY=
CLOUDINARY_API_SECRET=

# ─── MSG91 (OTP SMS) ────────────────────────────────
MSG91_AUTH_KEY=
MSG91_TEMPLATE_ID=

# ─── Client URLs ────────────────────────────────────
CLIENT_URL=$BASE_URL
NEXT_PUBLIC_API_URL=$BASE_URL/api/v1
NEXT_PUBLIC_APP_NAME=TripCompare
NEXT_PUBLIC_GOOGLE_CLIENT_ID=

# ─── Logging ────────────────────────────────────────
LOG_LEVEL=info
EOF

    echo -e "${GREEN}  Generated ${ENV_FILE} with strong random secrets${NC}"
    echo ""
    echo -e "${YELLOW}  ⚠️  IMPORTANT: Edit ${ENV_FILE} to add your API keys:${NC}"
    echo -e "     - Razorpay (RAZORPAY_KEY_ID, RAZORPAY_KEY_SECRET, RAZORPAY_WEBHOOK_SECRET)"
    echo -e "     - Cloudinary (CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET)"
    echo -e "     - Google OAuth (GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET)"
    echo -e "     - MSG91 (MSG91_AUTH_KEY, MSG91_TEMPLATE_ID)"
    echo ""
    read -p "  Press Enter to continue (or Ctrl+C to edit .env.prod first)..."
else
    echo -e "${GREEN}  ${ENV_FILE} already exists (preserving secrets)${NC}"
fi

# Read DOMAIN from env file (for HTTPS support)
DOMAIN=$(grep '^DOMAIN=' "$ENV_FILE" 2>/dev/null | cut -d'=' -f2 | tr -d ' ')
ACME_EMAIL=$(grep '^ACME_EMAIL=' "$ENV_FILE" 2>/dev/null | cut -d'=' -f2 | tr -d ' ')

if [ -n "$DOMAIN" ]; then
    TOTAL_STEPS=9  # override default
    echo -e "${GREEN}  HTTPS mode: domain=$DOMAIN${NC}"
else
    TOTAL_STEPS=8
fi

# ══════════════════════════════════════════════════════
# Step 5: Stop existing containers
# ══════════════════════════════════════════════════════
echo -e "${YELLOW}[5/$TOTAL_STEPS] Stopping existing containers...${NC}"
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" down 2>/dev/null || true
echo -e "${GREEN}  Done${NC}"

# ══════════════════════════════════════════════════════
# Step 6: Build images
# ══════════════════════════════════════════════════════
echo -e "${YELLOW}[6/$TOTAL_STEPS] Building Docker images...${NC}"
echo -e "  This may take 5-10 minutes on first build..."

docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" build api web

echo -e "${GREEN}  Images built successfully${NC}"

# Prune dangling images from previous builds
docker image prune -f 2>/dev/null || true

# ══════════════════════════════════════════════════════
# Step 7: Start databases + migrate
# ══════════════════════════════════════════════════════
echo -e "${YELLOW}[7/$TOTAL_STEPS] Starting databases and running migrations...${NC}"

# Start Postgres + Redis
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d postgres redis

# Wait for databases to be healthy
echo -e "  Waiting for databases..."
for i in $(seq 1 30); do
    PG_HEALTHY=$(docker inspect --format='{{.State.Health.Status}}' travel-postgres-prod 2>/dev/null || echo "starting")
    REDIS_HEALTHY=$(docker inspect --format='{{.State.Health.Status}}' travel-redis-prod 2>/dev/null || echo "starting")

    if [ "$PG_HEALTHY" = "healthy" ] && [ "$REDIS_HEALTHY" = "healthy" ]; then
        echo -e "${GREEN}  PostgreSQL: healthy | Redis: healthy${NC}"
        break
    fi

    if [ $i -eq 30 ]; then
        echo -e "${RED}  Databases failed to start in 60s${NC}"
        docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" logs postgres redis
        exit 1
    fi
    sleep 2
done

# Run migrations
echo -e "  Running Prisma migrations..."
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" --profile migrate run --rm migrate
echo -e "${GREEN}  Migrations complete${NC}"

# Seed (optional, skip on failure)
echo -e "  Seeding database..."
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" --profile seed run --rm seed 2>/dev/null \
    && echo -e "${GREEN}  Seed complete${NC}" \
    || echo -e "${YELLOW}  Seed skipped (already applied or no seed data)${NC}"

# ══════════════════════════════════════════════════════
# Step 8: Start all services
# ══════════════════════════════════════════════════════
echo -e "${YELLOW}[8/$TOTAL_STEPS] Starting all services...${NC}"

docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d

# Wait for health checks
echo -e "  Waiting for services to be healthy..."
for i in $(seq 1 40); do
    NGINX_HEALTHY=$(docker inspect --format='{{.State.Health.Status}}' travel-nginx-prod 2>/dev/null || echo "starting")

    if [ "$NGINX_HEALTHY" = "healthy" ]; then
        echo -e "${GREEN}  All services healthy!${NC}"
        break
    fi

    if [ $i -eq 40 ]; then
        echo -e "${YELLOW}  Health check timed out (80s). Services may still be starting.${NC}"
        break
    fi
    sleep 2
done

# ══════════════════════════════════════════════════════
# Step 9: Enable HTTPS (if DOMAIN is set)
# ══════════════════════════════════════════════════════
if [ -n "$DOMAIN" ]; then
    echo -e "${YELLOW}[9/9] Enabling HTTPS for $DOMAIN...${NC}"

    if [ -z "$ACME_EMAIL" ]; then
        echo -e "${RED}  ACME_EMAIL is required for Let's Encrypt. Set it in $ENV_FILE${NC}"
    else
        # Obtain/renew certificate via Certbot webroot (Nginx serves ACME challenge on :80)
        echo -e "  Requesting certificate from Let's Encrypt..."
        docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" --profile certbot run --rm certbot certonly \
            --webroot --webroot-path=/var/www/certbot \
            --email "$ACME_EMAIL" --agree-tos --no-eff-email \
            -d "$DOMAIN" --keep-until-expiring

        if [ $? -eq 0 ]; then
            # Swap to SSL Nginx template
            echo -e "  Activating HTTPS Nginx config..."
            cp docker/nginx/ssl.conf.template docker/nginx/templates/default.conf.template

            # Restart Nginx to load certs + HTTPS config
            docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" restart nginx
            sleep 5
            echo -e "${GREEN}  HTTPS enabled for $DOMAIN${NC}"
        else
            echo -e "${RED}  Certbot failed. Continuing with HTTP only.${NC}"
            echo -e "  Check DNS: A record for $DOMAIN must point to $SERVER_IP"
        fi
    fi
fi

# ══════════════════════════════════════════════════════
# Done — Print status
# ══════════════════════════════════════════════════════
echo ""
echo -e "${YELLOW}Service Status:${NC}"
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" ps
echo ""

echo -e "${CYAN}╔════════════════════════════════════════════╗"
echo -e "║   Production Deployment Complete!          ║"
echo -e "╚════════════════════════════════════════════╝${NC}"
echo ""

if [ -n "$DOMAIN" ]; then
    echo -e "Services:"
    echo -e "  ${GREEN}Web:${NC}     https://$DOMAIN"
    echo -e "  ${GREEN}API:${NC}     https://$DOMAIN/api/v1"
    echo -e "  ${GREEN}Health:${NC}  https://$DOMAIN/health"
else
    echo -e "Services:"
    echo -e "  ${GREEN}Web:${NC}     http://$SERVER_IP"
    echo -e "  ${GREEN}API:${NC}     http://$SERVER_IP/api/v1"
    echo -e "  ${GREEN}Health:${NC}  http://$SERVER_IP/health"
fi
echo ""
echo -e "Commands:"
echo -e "  docker compose --env-file $ENV_FILE -f $COMPOSE_FILE logs -f           ${CYAN}# All logs${NC}"
echo -e "  docker compose --env-file $ENV_FILE -f $COMPOSE_FILE logs -f api       ${CYAN}# API logs${NC}"
echo -e "  docker compose --env-file $ENV_FILE -f $COMPOSE_FILE restart api web   ${CYAN}# Restart app${NC}"
echo -e "  docker compose --env-file $ENV_FILE -f $COMPOSE_FILE down              ${CYAN}# Stop all${NC}"
echo -e "  docker compose --env-file $ENV_FILE -f $COMPOSE_FILE down -v           ${CYAN}# Stop + delete data${NC}"
echo ""
if [ -z "$DOMAIN" ]; then
    echo -e "${YELLOW}To enable HTTPS:${NC}"
    echo -e "  1. Point DNS A record to $SERVER_IP"
    echo -e "  2. Edit .env.prod: uncomment and set DOMAIN, ACME_EMAIL, SERVER_NAME"
    echo -e "  3. Update CLIENT_URL=https://yourdomain.com  NEXT_PUBLIC_API_URL=https://yourdomain.com/api/v1"
    echo -e "  4. Re-run: ./scripts/deploy-prod.sh"
    echo ""
fi
