#!/usr/bin/env bash
set -euo pipefail

# Travel App — Production Deployment
# Mirror of docker-up.sh but for prod (pre-built images, Nginx, migrations)
# Usage: ./scripts/deploy-prod.sh

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

COMPOSE_FILE="docker-compose.prod.yml"
ENV_FILE=".env.prod"
API_PORT=4001
WEB_PORT_HOST=3001

# ── Ensure Docker daemon is reachable ─────────────────
if ! docker info >/dev/null 2>&1; then
  echo "❌ Docker daemon is not running. Start it with: sudo systemctl start docker"
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "❌ Docker Compose V2 is not available."
  exit 1
fi

# ── Check/Create Swap (next build needs ~2GB RAM) ────
if command -v free &> /dev/null; then
  TOTAL_RAM_MB=$(free -m | awk '/Mem:/ {print $2}')
  if [ "$TOTAL_RAM_MB" -lt 3000 ] && [ ! -f /swapfile ]; then
    echo "⏳ Low RAM (${TOTAL_RAM_MB}MB). Creating 2GB swap..."
    sudo fallocate -l 2G /swapfile 2>/dev/null || sudo dd if=/dev/zero of=/swapfile bs=1M count=2048
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile
    grep -q '/swapfile' /etc/fstab 2>/dev/null || echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab > /dev/null
    echo "  ✅ Swap created"
  fi
fi

# ── Detect host IP ────────────────────────────────────
if [[ -z "${HOST_IP:-}" ]]; then
  SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || curl -s --max-time 5 ifconfig.me 2>/dev/null || echo "localhost")
  echo "🌐 Detected IP: $SERVER_IP"
  read -rp "   Use this IP? (y/n or enter custom): " INPUT_IP
  if [[ "$INPUT_IP" == "y" || "$INPUT_IP" == "Y" ]]; then
    HOST_IP="$SERVER_IP"
  elif [[ -n "$INPUT_IP" && "$INPUT_IP" != "n" && "$INPUT_IP" != "N" ]]; then
    HOST_IP="$INPUT_IP"
  else
    read -rp "   Enter server IP: " HOST_IP
  fi
fi

echo "   Using: $HOST_IP"

# ── Generate .env.prod (first run only) ──────────────
if [ ! -f "$ENV_FILE" ]; then
  echo ""
  echo "📝 Generating ${ENV_FILE} with strong secrets..."

  PG_PASS=$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)
  RD_PASS=$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)
  JWT_S=$(openssl rand -base64 48 | tr -d '/+=' | head -c 48)
  JWT_RS=$(openssl rand -base64 48 | tr -d '/+=' | head -c 48)
  BASE_URL="http://$HOST_IP"

  cat > "$ENV_FILE" << EOF
# ─── Auto-generated by deploy-prod.sh ────────────────
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Re-running deploy-prod.sh will NOT overwrite this file.

# ─── Server ──────────────────────────────────────────
SERVER_IP=$HOST_IP
SERVER_NAME=_
WEB_PORT=3000
# Set DOMAIN + ACME_EMAIL to enable HTTPS:
# DOMAIN=tripcompare.in
# ACME_EMAIL=you@email.com

# ─── Database ────────────────────────────────────────
POSTGRES_USER=travel_user
POSTGRES_PASSWORD=$PG_PASS
POSTGRES_DB=travel_prod

# ─── Redis ───────────────────────────────────────────
REDIS_PASSWORD=$RD_PASS

# ─── Auth ────────────────────────────────────────────
JWT_SECRET=$JWT_S
JWT_REFRESH_SECRET=$JWT_RS
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# ─── Razorpay ───────────────────────────────────────
RAZORPAY_KEY_ID=
RAZORPAY_KEY_SECRET=
RAZORPAY_WEBHOOK_SECRET=

# ─── Cloudinary ─────────────────────────────────────
CLOUDINARY_CLOUD_NAME=
CLOUDINARY_API_KEY=
CLOUDINARY_API_SECRET=

# ─── SMTP (Email OTP / Notifications) ───────────────
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=

# ─── MSG91 (OTP SMS) ────────────────────────────────
MSG91_AUTH_KEY=
MSG91_TEMPLATE_ID=

# ─── Firebase (Phone Auth — optional) ───────────────
FIREBASE_PROJECT_ID=
FIREBASE_CLIENT_EMAIL=
FIREBASE_PRIVATE_KEY=
NEXT_PUBLIC_FIREBASE_API_KEY=
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=
NEXT_PUBLIC_FIREBASE_PROJECT_ID=
NEXT_PUBLIC_FIREBASE_APP_ID=
NEXT_PUBLIC_PHONE_AUTH_STRATEGY=backend

# ─── Client URLs ────────────────────────────────────
CLIENT_URL=$BASE_URL
NEXT_PUBLIC_API_URL=$BASE_URL/api/v1
NEXT_PUBLIC_SOCKET_URL=$BASE_URL
NEXT_PUBLIC_APP_NAME=TripCompare
NEXT_PUBLIC_GOOGLE_CLIENT_ID=

# ─── Logging ────────────────────────────────────────
LOG_LEVEL=info
EOF

  echo "  ✅ Generated ${ENV_FILE}"
  echo ""
  echo "  ⚠️  Edit ${ENV_FILE} to add API keys (Razorpay, Cloudinary, Google, MSG91)"
  read -rp "  Press Enter to continue (or Ctrl+C to edit first)..."
else
  echo "  ✅ ${ENV_FILE} already exists (preserving secrets)"
fi

# ── Domain configuration ──────────────────────────────
echo ""
echo "🌐 Domain configuration..."
EXISTING_DOMAIN=$(grep '^DOMAIN=' "$ENV_FILE" 2>/dev/null | head -1 | cut -d'=' -f2 | tr -d ' ' || true)

if [ -n "$EXISTING_DOMAIN" ]; then
  # Strip protocol and trailing slashes in case it was stored incorrectly
  DOMAIN=$(echo "$EXISTING_DOMAIN" | sed 's|^https\?://||' | sed 's|/.*||')
  echo "   ✅ Using domain from ${ENV_FILE}: $DOMAIN"
else
  read -rp "   No domain set. Enter domain (or leave empty to skip): " NEW_DOMAIN
  if [ -n "$NEW_DOMAIN" ]; then
    # Strip protocol and trailing slashes (user might type https://example.com)
    DOMAIN=$(echo "$NEW_DOMAIN" | sed 's|^https\?://||' | sed 's|/.*||')
  else
    DOMAIN=""
  fi
fi

# Persist domain + update related URLs in .env.prod
if [ -n "$DOMAIN" ]; then
  SCHEME="https"
  BASE_DOMAIN_URL="${SCHEME}://${DOMAIN}"

  # Helper: upsert a key=value in .env.prod
  _env_set() {
    local KEY="$1" VAL="$2"
    if grep -q "^${KEY}=" "$ENV_FILE" 2>/dev/null; then
      sed -i "s|^${KEY}=.*|${KEY}=${VAL}|" "$ENV_FILE"
    elif grep -q "^# *${KEY}=" "$ENV_FILE" 2>/dev/null; then
      # Uncomment and set
      sed -i "s|^# *${KEY}=.*|${KEY}=${VAL}|" "$ENV_FILE"
    else
      echo "${KEY}=${VAL}" >> "$ENV_FILE"
    fi
  }

  _env_set "DOMAIN" "$DOMAIN"
  _env_set "SERVER_NAME" "$DOMAIN"
  _env_set "CLIENT_URL" "$BASE_DOMAIN_URL"
  _env_set "NEXT_PUBLIC_API_URL" "${BASE_DOMAIN_URL}/api/v1"
  _env_set "NEXT_PUBLIC_SOCKET_URL" "$BASE_DOMAIN_URL"
  _env_set "NEXT_PUBLIC_SITE_URL" "$BASE_DOMAIN_URL"

  # Prompt for ACME_EMAIL if not set (needed for HTTPS)
  EXISTING_ACME=$(grep '^ACME_EMAIL=' "$ENV_FILE" 2>/dev/null | head -1 | cut -d'=' -f2 | tr -d ' ' || true)
  if [ -z "$EXISTING_ACME" ]; then
    read -rp "   Enter email for Let's Encrypt (ACME_EMAIL): " ACME_INPUT
    if [ -n "$ACME_INPUT" ]; then
      _env_set "ACME_EMAIL" "$ACME_INPUT"
    fi
  fi

  echo "   ✅ Domain set to $DOMAIN — URLs updated in ${ENV_FILE}"
else
  echo "   ⏭️  No domain configured (HTTP-only with IP)"
fi

# ── Validate critical secrets ───────────────────────
echo ""
echo "🔑 Validating critical secrets in ${ENV_FILE}..."
PATCHED=0

validate_secret() {
  local KEY="$1"
  local MIN_LEN="${2:-16}"
  local VAL
  VAL=$(grep "^${KEY}=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d'=' -f2- || true)

  if [ -z "$VAL" ] || [ "$VAL" = "CHANGE_ME_STRONG_PASSWORD" ] || [ "$VAL" = "CHANGE_ME_MIN_32_CHARS_LONG_SECRET" ]; then
    local NEW_VAL
    NEW_VAL=$(openssl rand -base64 48 | tr -d '/+=' | head -c "$MIN_LEN")
    if grep -q "^${KEY}=" "$ENV_FILE" 2>/dev/null; then
      sed -i "s|^${KEY}=.*|${KEY}=${NEW_VAL}|" "$ENV_FILE"
    else
      echo "${KEY}=${NEW_VAL}" >> "$ENV_FILE"
    fi
    echo "  🔧 ${KEY} — generated (was empty/placeholder)"
    PATCHED=$((PATCHED + 1))
  else
    echo "  ✅ ${KEY} — set"
  fi
}

validate_secret "POSTGRES_PASSWORD" 32
validate_secret "REDIS_PASSWORD" 32
validate_secret "JWT_SECRET" 48
validate_secret "JWT_REFRESH_SECRET" 48

if [ "$PATCHED" -gt 0 ]; then
  echo ""
  echo "  ⚠️  ${PATCHED} secret(s) were auto-generated. Review ${ENV_FILE} if needed."
fi

# Shorthand for all compose commands
# Note: --env-file handles variable interpolation; do NOT `source .env.prod`
# because FIREBASE_PRIVATE_KEY with PEM newlines will break bash sourcing.
DC="docker compose --env-file $ENV_FILE -f $COMPOSE_FILE"

echo ""
echo "🚀 Starting TravelApp Production..."
echo "   HOST: $HOST_IP"
echo ""

# ── Stop existing containers ──────────────────────────
$DC down --remove-orphans 2>/dev/null || true

# ── Build images ──────────────────────────────────────
echo "📦 Building images (first build may take 5-10 min)..."
$DC build api web

# Prune dangling images from previous builds
docker image prune -f 2>/dev/null || true

# ── Start databases ───────────────────────────────────
echo ""
echo "🗄️  Starting Postgres + Redis..."
$DC up -d postgres redis

# ── Wait for databases ────────────────────────────────
echo ""
echo "🔍 Waiting for databases..."
HEALTH_TIMEOUT=180
for svc in postgres redis; do
  elapsed=0
  container="travel-${svc}-prod"
  while [ $elapsed -lt $HEALTH_TIMEOUT ]; do
    status=$(docker inspect --format='{{if .State.Health}}{{.State.Health.Status}}{{else}}no-healthcheck{{end}}' "$container" 2>/dev/null || echo "missing")
    if [ "$status" = "healthy" ]; then
      echo "  ✅ ${svc} — healthy"
      break
    elif [ "$status" = "missing" ] || [ "$status" = "unhealthy" ]; then
      echo "  ❌ ${svc} — ${status}"
      $DC logs "$svc" --tail 15
      exit 1
    fi
    sleep 2
    elapsed=$((elapsed + 2))
  done
  if [ $elapsed -ge $HEALTH_TIMEOUT ]; then
    echo "  ⏰ ${svc} — timed out after ${HEALTH_TIMEOUT}s"
    exit 1
  fi
done

# ── Run migrations ────────────────────────────────────
echo ""
echo "🔧 Running Prisma migrations..."
$DC --profile migrate run --rm migrate
echo "  ✅ Migrations complete"

# ── Seed (optional) ──────────────────────────────────
echo "🌱 Seeding database..."
$DC --profile seed run --rm seed \
  && echo "  ✅ Seed complete" \
  || echo "  ⏭️  Seed skipped (already applied or no seed data)"

# ── Prepare Nginx template ───────────────────────────
# Use HTTP-only template until SSL certs exist (Certbot runs after health checks)
CERTS_EXIST=false
if [ -n "$DOMAIN" ]; then
  # Certs live inside Docker volume — check via a temp container
  if docker run --rm -v "$(docker volume ls -q | grep certbot_certs | head -1):/certs:ro" alpine \
    test -f "/certs/live/${DOMAIN}/fullchain.pem" 2>/dev/null; then
    CERTS_EXIST=true
  fi
fi

if [ "$CERTS_EXIST" = true ]; then
  echo "🔒 SSL certs found — using HTTPS template"
  cp docker/nginx/ssl.conf.template docker/nginx/templates/default.conf.template
else
  echo "🌐 No SSL certs yet — using HTTP-only template (Certbot will run after)"
  cp docker/nginx/templates/default.conf.template.http-only docker/nginx/templates/default.conf.template
fi

# ── Start all services ────────────────────────────────
echo ""
echo "🔧 Starting API + Web + Nginx..."
$DC up -d

# ── Health check all services ─────────────────────────
echo ""
echo "🔍 Checking service health..."
SERVICES=("api" "web" "nginx")
FAILED=()

for svc in "${SERVICES[@]}"; do
  elapsed=0
  container="travel-${svc}-prod"
  while [ $elapsed -lt $HEALTH_TIMEOUT ]; do
    status=$(docker inspect --format='{{if .State.Health}}{{.State.Health.Status}}{{else}}no-healthcheck{{end}}' "$container" 2>/dev/null || echo "missing")

    if [ "$status" = "healthy" ]; then
      echo "  ✅ ${svc} — healthy"
      break
    elif [ "$status" = "no-healthcheck" ]; then
      running=$(docker inspect --format='{{.State.Status}}' "$container" 2>/dev/null || echo "missing")
      if [ "$running" = "running" ]; then
        echo "  ✅ ${svc} — running (no healthcheck)"
        break
      else
        echo "  ❌ ${svc} — ${running}"
        FAILED+=("$svc")
        break
      fi
    elif [ "$status" = "missing" ]; then
      echo "  ❌ ${svc} — ${status}"
      FAILED+=("$svc")
      break
    fi
    # "starting" or "unhealthy" → keep waiting until timeout
    sleep 3
    elapsed=$((elapsed + 3))
  done

  if [ $elapsed -ge $HEALTH_TIMEOUT ] && [ "$status" != "healthy" ]; then
    echo "  ⏰ ${svc} — timed out after ${HEALTH_TIMEOUT}s (status: ${status})"
    FAILED+=("$svc")
  fi
done

if [ ${#FAILED[@]} -gt 0 ]; then
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "⚠️  Some services failed to start:"
  echo ""
  for svc in "${FAILED[@]}"; do
    echo "── travel-${svc}-prod ──────────────────────────"
    docker logs "travel-${svc}-prod" --tail 15 2>&1 || true
    echo ""
  done
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "Fix the issues above, then re-run: ./scripts/deploy-prod.sh"
  exit 1
fi

# ── Enable HTTPS (if DOMAIN is set) ──────────────────
ACME_EMAIL=$(grep '^ACME_EMAIL=' "$ENV_FILE" 2>/dev/null | cut -d'=' -f2 | tr -d ' ' || true)

if [ -n "$DOMAIN" ] && [ -n "$ACME_EMAIL" ]; then
  echo ""
  echo "🔒 Enabling HTTPS for $DOMAIN..."
  if $DC --profile certbot run --rm certbot certonly \
    --webroot --webroot-path=/var/www/certbot \
    --email "$ACME_EMAIL" --agree-tos --no-eff-email \
    -d "$DOMAIN" --keep-until-expiring; then
    cp docker/nginx/ssl.conf.template docker/nginx/templates/default.conf.template
    $DC restart nginx
    sleep 5
    echo "  ✅ HTTPS enabled for $DOMAIN"
  else
    echo "  ❌ Certbot failed. Continuing with HTTP."
  fi
fi

# ── Done ──────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ TravelApp Production is running!"
echo ""
if [ -n "${DOMAIN:-}" ]; then
  echo "  Frontend:   https://$DOMAIN"
  echo "  API:        https://$DOMAIN/api/v1"
  echo "  Health:     https://$DOMAIN/health"
else
  echo "  Nginx:      http://${HOST_IP}        (port 80)"
  echo "  Frontend:   http://${HOST_IP}:${WEB_PORT_HOST}"
  echo "  API:        http://${HOST_IP}:${API_PORT}"
  echo "  Health:     http://${HOST_IP}:${API_PORT}/health"
fi
echo ""
echo "  Logs:       $DC logs -f"
echo "  API logs:   $DC logs -f api"
echo "  Restart:    $DC restart api web nginx"
echo "  Stop:       $DC down"
echo "  Stop+data:  $DC down -v"
echo ""
if [ -z "${DOMAIN:-}" ]; then
  echo "To enable HTTPS:"
  echo "  1. Point DNS A record to $HOST_IP"
  echo "  2. Re-run: ./scripts/deploy-prod.sh (it will prompt for domain)"
  echo ""
fi
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
