#!/usr/bin/env bash
set -euo pipefail

# Travel App — Production Deployment
# Mirror of docker-up.sh but for prod (pre-built images, Nginx, migrations)
# Usage: ./scripts/deploy-prod.sh

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

COMPOSE_FILE="docker-compose.prod.yml"
ENV_FILE=".env.prod"
API_PORT=4001
WEB_PORT_HOST=3001

# ── Ensure Docker daemon is reachable ─────────────────
if ! docker info >/dev/null 2>&1; then
  echo "❌ Docker daemon is not running. Start it with: sudo systemctl start docker"
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "❌ Docker Compose V2 is not available."
  exit 1
fi

# ── Seed prompt (ask early so user isn't blocked later) ──
read -rp "🌱 Run database seed? (y/n) [n]: " RUN_SEED

# ── Database choice (auto-detect or ask) ──────────────
echo ""
EXISTING_DB_MODE=$(grep '^DB_MODE=' "$ENV_FILE" 2>/dev/null | head -1 | cut -d'=' -f2 || true)
if [ -n "$EXISTING_DB_MODE" ]; then
  DB_MODE="$EXISTING_DB_MODE"
  echo "🗄️  Database: ${DB_MODE} (from ${ENV_FILE})"
  read -rp "   Keep this? (y/n) [y]: " KEEP_DB
  if [[ "$KEEP_DB" == "n" || "$KEEP_DB" == "N" ]]; then
    EXISTING_DB_MODE=""
  fi
fi
if [ -z "$EXISTING_DB_MODE" ]; then
  echo "🗄️  Database options:"
  echo "   1) Docker Postgres (local, fast, recommended)"
  echo "   2) External URL (Neon, Supabase, etc.)"
  read -rp "   Choose [1]: " DB_CHOICE
  DB_CHOICE="${DB_CHOICE:-1}"
  if [ "$DB_CHOICE" = "2" ]; then
    DB_MODE="external"
  else
    DB_MODE="docker"
  fi
  # Persist choice in .env.prod if it already exists
  if [ -f "$ENV_FILE" ]; then
    if grep -q '^DB_MODE=' "$ENV_FILE" 2>/dev/null; then
      sed -i "s|^DB_MODE=.*|DB_MODE=${DB_MODE}|" "$ENV_FILE"
    else
      echo "DB_MODE=${DB_MODE}" >> "$ENV_FILE"
    fi
  fi
fi
echo "   → Using: ${DB_MODE}"

# ── Check/Create Swap (next build needs ~2GB RAM) ────
if command -v free &> /dev/null; then
  TOTAL_RAM_MB=$(free -m | awk '/Mem:/ {print $2}')
  SWAP_MB=$(free -m | awk '/Swap:/ {print $2}')
  if [ "$TOTAL_RAM_MB" -lt 4000 ] && [ "${SWAP_MB:-0}" -lt 1000 ]; then
    echo "⏳ Low RAM (${TOTAL_RAM_MB}MB, swap ${SWAP_MB:-0}MB). Creating 2GB swap..."
    sudo fallocate -l 2G /swapfile 2>/dev/null || sudo dd if=/dev/zero of=/swapfile bs=1M count=2048
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile
    grep -q '/swapfile' /etc/fstab 2>/dev/null || echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab > /dev/null
    echo "  ✅ Swap created"
  fi
fi

# ── Detect host IP ────────────────────────────────────
if [[ -z "${HOST_IP:-}" ]]; then
  SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || curl -s --max-time 5 ifconfig.me 2>/dev/null || echo "localhost")
  echo "🌐 Detected IP: $SERVER_IP"
  read -rp "   Use this IP? (y/n or enter custom): " INPUT_IP
  if [[ "$INPUT_IP" == "y" || "$INPUT_IP" == "Y" ]]; then
    HOST_IP="$SERVER_IP"
  elif [[ -n "$INPUT_IP" && "$INPUT_IP" != "n" && "$INPUT_IP" != "N" ]]; then
    HOST_IP="$INPUT_IP"
  else
    read -rp "   Enter server IP: " HOST_IP
  fi
fi

echo "   Using: $HOST_IP"

# ── Generate .env.prod (first run only) ──────────────
if [ ! -f "$ENV_FILE" ]; then
  echo ""
  echo "📝 Generating ${ENV_FILE} with strong secrets..."

  RD_PASS=$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)
  PG_PASS=$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)
  JWT_S=$(openssl rand -base64 48 | tr -d '/+=' | head -c 48)
  BASE_URL="http://$HOST_IP"

  # Database URLs depend on chosen mode
  if [ "$DB_MODE" = "docker" ]; then
    DB_URL="postgresql://travel:${PG_PASS}@postgres:5432/travel?schema=public"
    DIRECT="postgresql://travel:${PG_PASS}@postgres:5432/travel?schema=public"
    DB_BLOCK="# ─── Database (Docker Postgres — local) ──────────────
# Switch to external: change URLs + DB_MODE below, re-run deploy
DB_MODE=docker
DATABASE_URL=$DB_URL
DIRECT_URL=$DIRECT
POSTGRES_PASSWORD=$PG_PASS"
  else
    DB_BLOCK="# ─── Database (External — Neon/Supabase) ─────────────
# Get both URLs from your provider's console
DB_MODE=external
DATABASE_URL=CHANGE_ME_EXTERNAL_DB_URL
DIRECT_URL=CHANGE_ME_EXTERNAL_DIRECT_URL"
  fi

  cat > "$ENV_FILE" << EOF
# ─── Auto-generated by deploy-prod.sh ────────────────
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Re-running deploy-prod.sh will NOT overwrite this file.

# ─── Server ──────────────────────────────────────────
SERVER_IP=$HOST_IP
SERVER_NAME=_
WEB_PORT=3000
# Set DOMAIN + ACME_EMAIL to enable HTTPS:
# DOMAIN=tripcompare.in
# ACME_EMAIL=you@email.com

$DB_BLOCK

# ─── Redis ───────────────────────────────────────────
REDIS_PASSWORD=$RD_PASS

# ─── Auth ────────────────────────────────────────────
JWT_SECRET=$JWT_S
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# ─── Razorpay ───────────────────────────────────────
RAZORPAY_KEY_ID=
RAZORPAY_KEY_SECRET=
RAZORPAY_WEBHOOK_SECRET=

# ─── Cloudinary ─────────────────────────────────────
CLOUDINARY_CLOUD_NAME=
CLOUDINARY_API_KEY=
CLOUDINARY_API_SECRET=

# ─── SMTP (Email OTP / Notifications) ───────────────
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=

# ─── MSG91 (OTP SMS) ────────────────────────────────
MSG91_AUTH_KEY=
MSG91_TEMPLATE_ID=

# ─── Firebase (Phone Auth — optional) ───────────────
FIREBASE_PROJECT_ID=
FIREBASE_CLIENT_EMAIL=
FIREBASE_PRIVATE_KEY=
NEXT_PUBLIC_FIREBASE_API_KEY=
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=
NEXT_PUBLIC_FIREBASE_PROJECT_ID=
NEXT_PUBLIC_FIREBASE_APP_ID=
NEXT_PUBLIC_PHONE_AUTH_STRATEGY=backend

# ─── Client URLs ────────────────────────────────────
CLIENT_URL=$BASE_URL
NEXT_PUBLIC_API_URL=$BASE_URL/api/v1
NEXT_PUBLIC_SOCKET_URL=$BASE_URL
NEXT_PUBLIC_APP_NAME=TripCompare
NEXT_PUBLIC_GOOGLE_CLIENT_ID=

# ─── Logging ────────────────────────────────────────
LOG_LEVEL=info
EOF

  echo "  ✅ Generated ${ENV_FILE}"
  echo ""
  echo "  ⚠️  Edit ${ENV_FILE} to add API keys (Razorpay, Cloudinary, Google, MSG91)"
  read -rp "  Press Enter to continue (or Ctrl+C to edit first)..."
else
  echo "  ✅ ${ENV_FILE} already exists (preserving secrets)"
fi

# ── Domain configuration ──────────────────────────────
echo ""
echo "🌐 Domain configuration..."
EXISTING_DOMAIN=$(grep '^DOMAIN=' "$ENV_FILE" 2>/dev/null | head -1 | cut -d'=' -f2 | tr -d ' ' || true)

if [ -n "$EXISTING_DOMAIN" ]; then
  # Strip protocol and trailing slashes in case it was stored incorrectly
  DOMAIN=$(echo "$EXISTING_DOMAIN" | sed 's|^https\?://||' | sed 's|/.*||')
  echo "   ✅ Using domain from ${ENV_FILE}: $DOMAIN"
else
  read -rp "   No domain set. Enter domain (or leave empty to skip): " NEW_DOMAIN
  if [ -n "$NEW_DOMAIN" ]; then
    # Strip protocol and trailing slashes (user might type https://example.com)
    DOMAIN=$(echo "$NEW_DOMAIN" | sed 's|^https\?://||' | sed 's|/.*||')
  else
    DOMAIN=""
  fi
fi

# Persist domain + update related URLs in .env.prod
if [ -n "$DOMAIN" ]; then
  SCHEME="https"
  BASE_DOMAIN_URL="${SCHEME}://${DOMAIN}"

  # Helper: upsert a key=value in .env.prod
  _env_set() {
    local KEY="$1" VAL="$2"
    if grep -q "^${KEY}=" "$ENV_FILE" 2>/dev/null; then
      sed -i "s|^${KEY}=.*|${KEY}=${VAL}|" "$ENV_FILE"
    elif grep -q "^# *${KEY}=" "$ENV_FILE" 2>/dev/null; then
      # Uncomment and set
      sed -i "s|^# *${KEY}=.*|${KEY}=${VAL}|" "$ENV_FILE"
    else
      echo "${KEY}=${VAL}" >> "$ENV_FILE"
    fi
  }

  _env_set "DOMAIN" "$DOMAIN"
  _env_set "SERVER_NAME" "$DOMAIN"
  _env_set "CLIENT_URL" "$BASE_DOMAIN_URL"
  _env_set "NEXT_PUBLIC_API_URL" "${BASE_DOMAIN_URL}/api/v1"
  _env_set "NEXT_PUBLIC_SOCKET_URL" "$BASE_DOMAIN_URL"
  _env_set "NEXT_PUBLIC_SITE_URL" "$BASE_DOMAIN_URL"

  # Prompt for ACME_EMAIL if not set (needed for HTTPS)
  EXISTING_ACME=$(grep '^ACME_EMAIL=' "$ENV_FILE" 2>/dev/null | head -1 | cut -d'=' -f2 | tr -d ' ' || true)
  if [ -z "$EXISTING_ACME" ]; then
    read -rp "   Enter email for Let's Encrypt (ACME_EMAIL): " ACME_INPUT
    if [ -n "$ACME_INPUT" ]; then
      _env_set "ACME_EMAIL" "$ACME_INPUT"
    fi
  fi

  echo "   ✅ Domain set to $DOMAIN — URLs updated in ${ENV_FILE}"
else
  echo "   ⏭️  No domain configured (HTTP-only with IP)"
fi

# ── Validate critical secrets ───────────────────────
echo ""
echo "🔑 Validating critical secrets in ${ENV_FILE}..."
PATCHED=0

validate_secret() {
  local KEY="$1"
  local MIN_LEN="${2:-16}"
  local VAL
  VAL=$(grep "^${KEY}=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d'=' -f2- || true)

  if [ -z "$VAL" ] || [ "$VAL" = "CHANGE_ME_STRONG_PASSWORD" ] || [ "$VAL" = "CHANGE_ME_MIN_32_CHARS_LONG_SECRET" ]; then
    local NEW_VAL
    NEW_VAL=$(openssl rand -base64 48 | tr -d '/+=' | head -c "$MIN_LEN")
    if grep -q "^${KEY}=" "$ENV_FILE" 2>/dev/null; then
      sed -i "s|^${KEY}=.*|${KEY}=${NEW_VAL}|" "$ENV_FILE"
    else
      echo "${KEY}=${NEW_VAL}" >> "$ENV_FILE"
    fi
    echo "  🔧 ${KEY} — generated (was empty/placeholder)"
    PATCHED=$((PATCHED + 1))
  else
    echo "  ✅ ${KEY} — set"
  fi
}

validate_secret "REDIS_PASSWORD" 32
validate_secret "JWT_SECRET" 48
if [ "$DB_MODE" = "docker" ]; then
  validate_secret "POSTGRES_PASSWORD" 32
fi

# Razorpay: if key is set the webhook secret must also be set (empty HMAC secret
# accepts any caller — see backend P0-3 in backend-audit.md)
RAZORPAY_KEY=$(grep "^RAZORPAY_KEY_ID=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d'=' -f2- || true)
if [ -n "$RAZORPAY_KEY" ]; then
  RAZORPAY_WH=$(grep "^RAZORPAY_WEBHOOK_SECRET=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d'=' -f2- || true)
  if [ -z "$RAZORPAY_WH" ]; then
    echo "  ❌ RAZORPAY_WEBHOOK_SECRET — empty but RAZORPAY_KEY_ID is set"
    echo "     Payment webhooks will accept any caller without a secret."
    echo "     Add RAZORPAY_WEBHOOK_SECRET to ${ENV_FILE} and re-run."
    exit 1
  fi
  echo "  ✅ RAZORPAY_WEBHOOK_SECRET — set"
fi

if [ "$PATCHED" -gt 0 ]; then
  echo ""
  echo "  ⚠️  ${PATCHED} secret(s) were auto-generated. Review ${ENV_FILE} if needed."
fi

# ── Ensure Docker Postgres DB URLs match POSTGRES_PASSWORD ──
if [ "$DB_MODE" = "docker" ]; then
  PG_PW=$(grep "^POSTGRES_PASSWORD=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d'=' -f2- || true)
  EXPECTED_DB="postgresql://travel:${PG_PW}@postgres:5432/travel?schema=public"
  for KEY in DATABASE_URL DIRECT_URL; do
    CURRENT=$(grep "^${KEY}=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d'=' -f2- || true)
    if [ -z "$CURRENT" ] || [[ "$CURRENT" == *"CHANGE_ME"* ]] || [[ "$CURRENT" != *"${PG_PW}"* ]]; then
      if grep -q "^${KEY}=" "$ENV_FILE" 2>/dev/null; then
        sed -i "s|^${KEY}=.*|${KEY}=${EXPECTED_DB}|" "$ENV_FILE"
      else
        echo "${KEY}=${EXPECTED_DB}" >> "$ENV_FILE"
      fi
      echo "  🔧 ${KEY} — synced with POSTGRES_PASSWORD"
    fi
  done
fi

# ── Validate database URLs ────────────────────────────
echo ""
echo "🗄️  Validating database URLs in ${ENV_FILE}..."

validate_db_url() {
  local KEY="$1"
  local VAL
  VAL=$(grep "^${KEY}=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d'=' -f2- || true)
  if [ -z "$VAL" ] || [[ "$VAL" == *"CHANGE_ME"* ]]; then
    echo "  ❌ ${KEY} — not configured."
    if [ "$DB_MODE" = "docker" ]; then
      echo "     Delete ${ENV_FILE} and re-run to auto-generate Docker Postgres URLs."
    else
      echo "     Set it to your external DB URL (e.g., Neon, Supabase)."
    fi
    exit 1
  fi
  if [[ "$VAL" != postgresql://* ]] && [[ "$VAL" != postgres://* ]]; then
    echo "  ❌ ${KEY} — must start with postgresql:// or postgres://"
    exit 1
  fi
  echo "  ✅ ${KEY} — set"
}

validate_db_url "DATABASE_URL"
validate_db_url "DIRECT_URL"

# Shorthand for all compose commands
# Note: --env-file handles variable interpolation; do NOT `source .env.prod`
# because FIREBASE_PRIVATE_KEY with PEM newlines will break bash sourcing.
if [ "$DB_MODE" = "docker" ]; then
  DC="docker compose --env-file $ENV_FILE -f $COMPOSE_FILE --profile db"
else
  DC="docker compose --env-file $ENV_FILE -f $COMPOSE_FILE"
fi

echo ""
echo "🚀 Starting TravelApp Production..."
echo "   HOST: $HOST_IP"
echo "   DB:   $DB_MODE"
echo ""

# ── Image versioning (git SHA for rollback) ──────────
GIT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
echo "📌 Git SHA: $GIT_SHA"
HEALTH_TIMEOUT=180

# ── Reusable health-wait helper ───────────────────────
# Waits until a container reports healthy (or no-healthcheck + running).
# Exits the script on unhealthy/missing/timeout.
_wait_healthy() {
  local svc="$1" container="$2" elapsed=0
  echo "  ⏳ Waiting for ${svc}..."
  while [ $elapsed -lt $HEALTH_TIMEOUT ]; do
    status=$(docker inspect --format='{{if .State.Health}}{{.State.Health.Status}}{{else}}no-healthcheck{{end}}' "$container" 2>/dev/null || echo "missing")
    if [ "$status" = "healthy" ]; then
      echo "  ✅ ${svc} — healthy"
      return 0
    elif [ "$status" = "no-healthcheck" ]; then
      running=$(docker inspect --format='{{.State.Status}}' "$container" 2>/dev/null || echo "missing")
      if [ "$running" = "running" ]; then echo "  ✅ ${svc} — running"; return 0; fi
    elif [ "$status" = "unhealthy" ] || [ "$status" = "missing" ]; then
      echo "  ❌ ${svc} — ${status}"
      $DC logs "$svc" --tail 20 2>/dev/null || true
      exit 1
    fi
    sleep 5; elapsed=$((elapsed + 5))
  done
  echo "  ⏰ ${svc} — timed out after ${HEALTH_TIMEOUT}s"
  exit 1
}

# ── Build API image (old containers stay up — zero build-time downtime) ──
echo "📦 Building API image..."
$DC build api

# Tag with git SHA for rollback capability
docker tag travel-api:prod "travel-api:$GIT_SHA" 2>/dev/null || true
docker image prune -f 2>/dev/null || true

# ── Stop existing containers (start of actual downtime) ──
$DC down --remove-orphans 2>/dev/null || true

# ── Start infrastructure (Redis + optional Postgres) ──
echo ""
if [ "$DB_MODE" = "docker" ]; then
  echo "🗄️  Starting Postgres + Redis..."
  $DC up -d postgres redis
else
  echo "🗄️  Starting Redis..."
  $DC up -d redis
fi

# ── Wait for infrastructure health ────────────────────
echo ""
echo "🔍 Waiting for infrastructure..."
if [ "$DB_MODE" = "docker" ]; then
  _wait_healthy postgres travel-postgres-prod
fi
_wait_healthy redis travel-redis-prod

# ── Backup database before migration ──────────────────
if [ "$DB_MODE" = "docker" ]; then
  echo ""
  echo "📸 Backing up database before migration..."
  BACKUP_DIR="/var/backups/travel"
  # Fall back to repo root if we can't write to /var/backups (non-root deploy users).
  # The repo root is a worse location but avoids aborting the deploy under set -e.
  mkdir -p "$BACKUP_DIR" 2>/dev/null || BACKUP_DIR="$ROOT_DIR"
  BACKUP_FILE="${BACKUP_DIR}/backup_$(date +%Y%m%d_%H%M%S).sql.gz"
  if docker exec travel-postgres-prod pg_dump -U "${POSTGRES_USER:-travel}" travel 2>/dev/null | gzip > "$BACKUP_FILE"; then
    BACKUP_SIZE=$(du -h "$BACKUP_FILE" 2>/dev/null | cut -f1)
    echo "  ✅ Backup saved: $BACKUP_FILE ($BACKUP_SIZE)"
    # Keep last 5 backups — remove older ones
    ls -t "${BACKUP_DIR}"/backup_*.sql.gz 2>/dev/null | tail -n +6 | xargs rm -f 2>/dev/null || true
  else
    rm -f "$BACKUP_FILE"
    echo "  ⚠️  Backup failed (new DB or empty). Continuing..."
  fi
fi

# ── Run migrations ─────────────────────────────────────
echo ""
echo "🔧 Running Prisma migrations..."
$DC --profile migrate run --rm migrate
echo "  ✅ Migrations complete"

# ── Seed (optional — answered at start) ───────────────
echo ""
if [[ "$RUN_SEED" == "y" || "$RUN_SEED" == "Y" ]]; then
  echo "🌱 Seeding database..."
  $DC --profile seed run --rm seed \
    && echo "  ✅ Seed complete" \
    || echo "  ⚠️  Seed failed — check logs above"
else
  echo "  ⏭️  Seed skipped"
fi

# ── Start API (must be healthy before building web) ────
# The web image build runs `next build` with --network=host so ISR pages can
# prerender against the live API (http://127.0.0.1:4001/api/v1).
echo ""
echo "🔧 Starting API..."
$DC up -d api
_wait_healthy api travel-api-prod

# ── Build Web image (API is live — ISR prerenders get real data) ──
echo ""
echo "📦 Building Web image..."
$DC build web

# Tag with git SHA for rollback capability
docker tag travel-web:prod "travel-web:$GIT_SHA" 2>/dev/null || true
docker image prune -f 2>/dev/null || true

# ── Prepare Nginx template ───────────────────────
# Use HTTP-only template until SSL certs exist (Certbot runs after health checks)
CERTS_EXIST=false
if [ -n "$DOMAIN" ]; then
  # Certs live inside Docker volume — check via a temp container
  if docker run --rm -v "$(docker volume ls -q | grep certbot_certs | head -1):/certs:ro" alpine \
    test -f "/certs/live/${DOMAIN}/fullchain.pem" 2>/dev/null; then
    CERTS_EXIST=true
  fi
fi

if [ "$CERTS_EXIST" = true ]; then
  echo "🔒 SSL certs found — using HTTPS template"
  cp docker/nginx/ssl.conf.template docker/nginx/templates/default.conf.template
else
  echo "🌐 No SSL certs yet — using HTTP-only template (Certbot will run after)"
  cp docker/nginx/templates/default.conf.template.http-only docker/nginx/templates/default.conf.template
fi

# ── Start Web + Nginx ─────────────────────────────
echo ""
echo "🔧 Starting Web + Nginx..."
$DC up -d web nginx

# ── Health check all services (parallel) ─────────────
echo ""
echo "🔍 Checking service health..."
TMPDIR_HEALTH=$(mktemp -d)

_check_svc() {
  local svc="$1" timeout="$2" out="$TMPDIR_HEALTH/${svc}.result"
  local container="travel-${svc}-prod"
  local elapsed=0 status
  while [ $elapsed -lt "$timeout" ]; do
    status=$(docker inspect --format='{{if .State.Health}}{{.State.Health.Status}}{{else}}no-healthcheck{{end}}' "$container" 2>/dev/null || echo "missing")
    if [ "$status" = "healthy" ]; then
      echo "ok" > "$out"; return
    elif [ "$status" = "no-healthcheck" ]; then
      running=$(docker inspect --format='{{.State.Status}}' "$container" 2>/dev/null || echo "missing")
      if [ "$running" = "running" ]; then echo "ok" > "$out"; else echo "fail:$running" > "$out"; fi
      return
    elif [ "$status" = "missing" ] || [ "$status" = "unhealthy" ]; then
      echo "fail:$status" > "$out"; return
    fi
    sleep 3; elapsed=$((elapsed + 3))
  done
  echo "timeout:$status" > "$out"
}

for svc in api web nginx; do
  _check_svc "$svc" "$HEALTH_TIMEOUT" &
done
wait

FAILED=()
for svc in api web nginx; do
  result=$(cat "$TMPDIR_HEALTH/${svc}.result" 2>/dev/null || echo "fail:missing")
  if [ "$result" = "ok" ]; then
    echo "  ✅ ${svc} — healthy"
  else
    echo "  ❌ ${svc} — ${result#*:}"
    FAILED+=("$svc")
  fi
done
rm -rf "$TMPDIR_HEALTH"

if [ ${#FAILED[@]} -gt 0 ]; then
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "⚠️  Some services failed to start:"
  echo ""
  for svc in "${FAILED[@]}"; do
    echo "── travel-${svc}-prod ──────────────────────────"
    docker logs "travel-${svc}-prod" --tail 15 2>&1 || true
    echo ""
  done
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "Fix the issues above, then re-run: ./scripts/deploy-prod.sh"
  exit 1
fi

# ── Enable HTTPS (if DOMAIN is set) ──────────────────
ACME_EMAIL=$(grep '^ACME_EMAIL=' "$ENV_FILE" 2>/dev/null | cut -d'=' -f2 | tr -d ' ' || true)

if [ -n "$DOMAIN" ] && [ -n "$ACME_EMAIL" ]; then
  echo ""
  echo "🔒 Enabling HTTPS for $DOMAIN..."
  if $DC --profile certbot run --rm certbot certonly \
    --webroot --webroot-path=/var/www/certbot \
    --email "$ACME_EMAIL" --agree-tos --no-eff-email \
    -d "$DOMAIN" --keep-until-expiring; then
    cp docker/nginx/ssl.conf.template docker/nginx/templates/default.conf.template
    # Graceful reload preserves active connections (vs restart which drops them)
    docker exec travel-nginx-prod nginx -s reload 2>/dev/null || $DC restart nginx
    sleep 3
    echo "  ✅ HTTPS enabled for $DOMAIN"

    # ── Set up certbot auto-renewal cron ────────────
    CRON_CMD="0 3 1,15 * * cd $ROOT_DIR && $DC --profile certbot run --rm certbot renew --quiet && docker exec travel-nginx-prod nginx -s reload"
    if ! crontab -l 2>/dev/null | grep -qF 'certbot renew'; then
      (crontab -l 2>/dev/null; echo "$CRON_CMD") | crontab -
      echo "  ✅ Certbot auto-renewal cron installed (1st & 15th of each month, 3 AM)"
    else
      echo "  ✅ Certbot auto-renewal cron already exists"
    fi
  else
    echo "  ❌ Certbot failed. Continuing with HTTP."
  fi
fi

# ── Done ──────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ TravelApp Production is running!"
echo "   DB: ${DB_MODE} $([ "$DB_MODE" = "docker" ] && echo "(local Postgres container)" || echo "(external)")"
echo ""
if [ -n "${DOMAIN:-}" ]; then
  echo "  Frontend:   https://$DOMAIN"
  echo "  API:        https://$DOMAIN/api/v1"
  echo "  Health:     https://$DOMAIN/health"
else
  echo "  Nginx:      http://${HOST_IP}        (port 80 — public)"
  echo "  Health:     http://${HOST_IP}/health"
  echo "  (API/web ports 4001/3001 are loopback-only — access via nginx on port 80)"
fi
echo ""
echo "  Image tag:  $GIT_SHA"
echo "  Logs:       $DC logs -f"
echo "  API logs:   $DC logs -f api"
echo "  Restart:    $DC restart api web nginx"
echo "  Stop:       $DC down"
echo "  Stop+data:  $DC down -v"
echo "  Rollback:   docker tag travel-api:<sha> travel-api:prod && docker tag travel-web:<sha> travel-web:prod && $DC up -d api web"
echo ""
if [ -z "${DOMAIN:-}" ]; then
  echo "To enable HTTPS:"
  echo "  1. Point DNS A record to $HOST_IP"
  echo "  2. Re-run: ./scripts/deploy-prod.sh (it will prompt for domain)"
  echo ""
fi
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
