-- No-op: trendingScore DOUBLE PRECISION was already added by migration 20260629215303.
-- This migration was generated when the column type was briefly changed to INTEGER,
-- then reverted. The schema is back to Float? (DOUBLE PRECISION) so no action needed.
